/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YhteystiedotRouteImport } from './routes/yhteystiedot'
import { Route as PalvelutRouteImport } from './routes/palvelut'
import { Route as IndexRouteImport } from './routes/index'

const YhteystiedotRoute = YhteystiedotRouteImport.update({
  id: '/yhteystiedot',
  path: '/yhteystiedot',
  getParentRoute: () => rootRouteImport,
} as any)
const PalvelutRoute = PalvelutRouteImport.update({
  id: '/palvelut',
  path: '/palvelut',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/palvelut': typeof PalvelutRoute
  '/yhteystiedot': typeof YhteystiedotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/palvelut': typeof PalvelutRoute
  '/yhteystiedot': typeof YhteystiedotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/palvelut': typeof PalvelutRoute
  '/yhteystiedot': typeof YhteystiedotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/palvelut' | '/yhteystiedot'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/palvelut' | '/yhteystiedot'
  id: '__root__' | '/' | '/palvelut' | '/yhteystiedot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PalvelutRoute: typeof PalvelutRoute
  YhteystiedotRoute: typeof YhteystiedotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yhteystiedot': {
      id: '/yhteystiedot'
      path: '/yhteystiedot'
      fullPath: '/yhteystiedot'
      preLoaderRoute: typeof YhteystiedotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palvelut': {
      id: '/palvelut'
      path: '/palvelut'
      fullPath: '/palvelut'
      preLoaderRoute: typeof PalvelutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PalvelutRoute: PalvelutRoute,
  YhteystiedotRoute: YhteystiedotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
